name: Check latest Lens version

on:
  schedule:
    - cron: '15 10 * * *'
  workflow_dispatch:

jobs:
  version_check:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3.2.0
        with:
          token: ${{ secrets.PAT }}
      - name: Get the latest version of Lens
        run: |
          curl -s https://api.github.com/repos/lensapp/lens/releases | jq -r '[.[] | select(.prerelease == false)][0] | .tag_name[1:]' > version
          export LENS_VERSION=$(cat version)
          echo "LENS_VERSION=${LENS_VERSION}"
          if [[ -n "${LENS_VERSION}" ]]; then echo "LENS_VERSION=${LENS_VERSION}" >> ${GITHUB_ENV}; else exit 1; fi
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.0.0
        with:
          message: 'Version updated to: ${{ env.LENS_VERSION }}'
